version: "3"
services:
  ss1:
    image: shadowsocks/shadowsocks-libev
    restart: always
    ports:
      - "9000:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=shadowsocks
    networks:
      - ss
  ss2:
    image: shadowsocks/shadowsocks-libev
    restart: always
    ports:
      - "9001:8388"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=shadowsocks
    networks:
      - ss
networks: 
  ss: